@@html:
<head>
<link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/spacelab/bootstrap.min.css" rel="stylesheet" integrity="sha384-sZG5VVk41YqhJjYXgJFoRVd3d2AdDgy4oyIytQJMGx/Mizz1N+5bgKQBSCGfKQnP" crossorigin="anonymous">
<link href="documentation.css" type="text/css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans" rel="stylesheet"> 
</head>
@@

Documentation for the C Linear Algebra library 

* OVERVIEW 

The main goal of this library is to provide an API that simplifies the development 
of powerful software applications, such as OpenGL/Vulkan 3D games and engineering
tools. 

The focus of this library is on matrix analysis, but more abstract functionalities
suitable for scientific computing are also implemented. 

There are several reasons to why C has been chosen for this project. 
1. Performance. C can achieve excellent performance by talking closely to hardware. 
2. Portability. C applications can be easily compiled on most modern operating systems.
3. Familiarity. C is a tiny part of C++, which is the lingua franca of games development. 

Code is benchmarked and a CMake script to build the library on any platform 
that supports it is available.



* DEPENDENCIES
| Library | Ubuntu package(s) |
| Cunit   | libcunit1-dev     |

* REFERENCE
** Linear Algebra
[[www.amazon.com/Introduction-Linear-Algebra-Gilbert-Strang/dp/0980232775][Introduction to Linear Algebra, Fifth Edition]]

** OpenGL
[[learnopengl.com][Learn OpenGL]]
[[github.com/capnramses/antons_opengl_tutorials_book][Anton's OpenGL Tutorials]]




